#spring.application.name=ApiUser

server:
  port: 8080
  servlet:
    context-path: /apiUser
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/apiUser_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
jwt:
    signerKey: "1EYK1xVZ5RTVIk50cVXTXtKMaSN8n5vpuR1rYRJQbad1yvX2OEbb+YbGvPXGKl96"